/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'template appliance' abstraction used by the templates.
// Some peripherals are on-board on the RDB, while other peripherals must be attached
// externally if needed.
// See https://aka.ms/AzureSphereHardwareDefinitions for more information on how to use
// hardware abstractions to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../template_appliance.json. Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// MT3620 RDB: Button A
#define BUTTON_A MT3620_RDB_BUTTON_A

// MT3620 RDB: Button B
#define BUTTON_B MT3620_RDB_BUTTON_B

// // Alert LED
// #define ALERT_LED MT3620_RDB_LED1_RED

// // MT3620 RDB: LED 1
// #define LED1 MT3620_RDB_LED1_GREEN

// // MT3620 RDB: LED 2
// #define LED2 MT3620_RDB_LED4_BLUE

// MT3620 RDB: Network Connected
#define NETWORK_CONNECTED_LED MT3620_RDB_NETWORKING_LED_GREEN 

// MT3620 RDB: Grove Relay
#define RELAY MT3620_RDB_HEADER1_PIN4_GPIO

// ISU0 UART is exposed on header 2, pin 1 (RX), pin 3 (TX), pin 5 (CTS), pin 7 (RTS)
#define UART0 MT3620_RDB_HEADER2_ISU0_UART

// ISU0 I2C is exposed on header 2, pin 1 (SDA) and pin 7 (SCL)
// #define I2cMaster2 MT3620_RDB_HEADER2_ISU0_I2C 

// MT3620 ADC CONTROLLER 0: channel 0 on pin 41, channel 1 on pin 42, channel 2 on pin 43, channel 3 on pin 44, channel 4 on pin 45, channel 5 on pin 46, channel 6 on pin 47, and channel 7 on pin 48. Pins for this controller are shared with GPIO41, GPIO42, GPIO43, GPIO44, GPIO45, GPIO46, GPIO47 and GPIO48. If this ADC controller is requested, none of these GPIOs can be used.
#define Adc MT3620_RDB_ADC_CONTROLLER0

// MT3620 RDB: LED 1
#define LED1_RED MT3620_RDB_LED1_RED

// MT3620 RDB: LED 1
#define LED1_GREEN MT3620_RDB_LED1_GREEN

// MT3620 RDB: LED 1
#define LED1_BLUE MT3620_RDB_LED1_BLUE 

// MT3620 RDB: LED 2 
#define LED2_RED MT3620_RDB_LED2_RED 

// MT3620 RDB: LED 2 
#define LED2_GREEN MT3620_RDB_LED2_GREEN 

// MT3620 RDB: LED 2 
#define LED2_BLUE MT3620_RDB_LED2_BLUE 

// MT3620 RDB: LED 3
#define LED3_RED MT3620_RDB_LED3_RED 

// MT3620 RDB: I2C0 is exposed on header 2, pin 1 (SDA) and pin 7 (SCL)
// Connect with sensor1 
#define I2C0 MT3620_RDB_HEADER2_ISU0_I2C 

//MT3620 RDB: ISU1 I2C is exposed on header 4, pin 5 (SDA) and pin 11 (SCL)
// Connect with sensor2 
#define I2C1 MT3620_RDB_HEADER4_ISU1_I2C 
